name: CobblestoneCitizens
version: '0.1.0-SNAPSHOT'
description: Cobblestone integration for Citizens — navigate to any NPC.
author: whimxiqal
website: https://cobblestonemc.org
main: org.cobblestonemc.integration.citizens.CobblestoneCitizensPlugin
api-version: '1.21'
folia-supported: false
dependencies:
  server:
    cobblestone:
      load: BEFORE
    Citizens:
      load: BEFORE
