name: CobblestoneEssentials
version: '0.1.0-SNAPSHOT'
description: Cobblestone integration for EssentialsX — navigate to /home and /spawn.
author: whimxiqal
website: https://cobblestonemc.org
main: org.cobblestonemc.integration.essentials.CobblestoneEssentialsPlugin
api-version: '1.21'
folia-supported: false
dependencies:
  server:
    cobblestone:
      load: BEFORE
    Essentials:
      load: BEFORE
