[versions]
adventure = "4.17.0"
paper = "26.1.2.build.+"
sponge = "12.0.0"
snakeyaml = "2.3"
shadow = "9.0.0"
h2 = "2.2.224"
bstats = "3.2.1"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
spongeapi = { module = "org.spongepowered:spongeapi", version.ref = "sponge" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
bstats-base = { module = "org.bstats:bstats-base", version.ref = "bstats" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-sponge = { module = "org.bstats:bstats-sponge", version.ref = "bstats" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
