name: CobblestoneBeautyQuests
version: '0.1.0-SNAPSHOT'
description: Cobblestone integration for BeautyQuests — guide players to their quest stages.
author: whimxiqal
website: https://cobblestonemc.org
main: org.cobblestonemc.integration.beautyquests.CobblestoneBeautyQuestsPlugin
api-version: '1.21'
folia-supported: false
dependencies:
  server:
    cobblestone:
      load: BEFORE
    BeautyQuests:
      load: BEFORE
